spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      auto-index-creation: true
      database: url-storage
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

url-shortener:
  short-url-prefix: "http://localhost:8080/urls/shortUrl/"
  redis:
    expiration-time: 30 # TTL in minutes